name: projeto_gbb_demo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.1.11 
  web_socket_channel: ^3.0.1
  uuid: ^4.5.1
  provider: ^6.0.5
  bonfire: 
    path: ./bonfire-3.10.0-hijacking/
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # - assets/images/
    # - assets/images/maps/
    # - assets/images/player/
    # - assets/images/enemies/
    # - assets/images/abilities/

    - assets/images/
    - assets/images/tutorialNPCs/
    - assets/images/tutorialNPCs/tutorial_farmer/neutral_farmer/
    - assets/images/tutorialNPCs/tutorial_farmer/communist_farmer/
    - assets/images/tutorialNPCs/tutorial_farmer/neutral_shepard/
    - assets/images/objects/
    - assets/images/objects/anvil_minigame/
    - assets/images/objects/launch_station/
    - assets/images/objects/sword_box/
    - assets/images/objects/smithing_table/
    - assets/images/objects/wheat_fields/
    - assets/images/communist/blacksmith/
    - assets/images/communist/blacksmith/armed/
    - assets/images/communist/blacksmith/armed/armored/
    - assets/images/communist/blacksmith/unarmed/
    - assets/images/capitalist/
    - assets/images/loyalist/
    - assets/images/map/
    - assets/images/map/house_interior/yellow_house/
    - assets/images/items/
    - assets/images/interface/
    - assets/images/ruins_village_map/
    - assets/images/interface/lifebar/
    - assets/images/interface/inventorybar/
    - assets/images/interface/minimap/
    - assets/images/background/
    - assets/images/attack_sprites/
    - assets/images/minigame/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
